<?xml version="1.0" encoding="utf-8"?><Database Name="ECMS" Class="System_adminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPYOP-CR7\SQLEXPRESS;Initial Catalog=ECMS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SYSTEM_ADMINS" Member="SYSTEM_ADMINS">
    <Type Name="SYSTEM_ADMINS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCTORS" Member="DOCTORS">
    <Type Name="DOCTORS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start_year_of_work" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>