<?xml version="1.0" encoding="utf-8"?><Database Name="ECMS" Class="ECMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPYOP-CR7\SQLEXPRESS;Initial Catalog=ECMS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.APPLICATIONS" Member="APPLICATIONS">
    <Type Name="APPLICATIONS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="patient_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="doctor_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="accepted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sympotoms" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="doucments_path" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="APPLICATIONS_EXAMINATIONS" Member="EXAMINATIONS" ThisKey="id" OtherKey="application_id" Type="EXAMINATIONS" />
      <Association Name="DOCTORS_APPLICATIONS" Member="DOCTORS" ThisKey="doctor_id" OtherKey="id" Type="DOCTORS" IsForeignKey="true" />
      <Association Name="PATIENT_APPLICATIONS" Member="PATIENT" ThisKey="patient_id" OtherKey="id" Type="PATIENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCTOR_OPENTIMES" Member="DOCTOR_OPENTIMES">
    <Type Name="DOCTOR_OPENTIMES">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="start" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="[end]" Member="end" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="DOCTORS_DOCTOR_OPENTIMES" Member="DOCTORS" ThisKey="doctor_id" OtherKey="id" Type="DOCTORS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCTORS" Member="DOCTORS">
    <Type Name="DOCTORS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start_year_of_work" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DOCTORS_APPLICATIONS" Member="APPLICATIONS" ThisKey="id" OtherKey="doctor_id" Type="APPLICATIONS" />
      <Association Name="DOCTORS_DOCTOR_OPENTIMES" Member="DOCTOR_OPENTIMES" ThisKey="id" OtherKey="doctor_id" Type="DOCTOR_OPENTIMES" />
      <Association Name="DOCTORS_SPECIALIZATIONS_OF_DOCTORS" Member="SPECIALIZATIONS_OF_DOCTORS" ThisKey="id" OtherKey="doctor_id" Type="SPECIALIZATIONS_OF_DOCTORS" />
    </Type>
  </Table>
  <Table Name="dbo.SYSTEM_ADMINS" Member="SYSTEM_ADMINS">
    <Type Name="SYSTEM_ADMINS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EXAMINATIONS" Member="EXAMINATIONS">
    <Type Name="EXAMINATIONS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="application_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="doucments_path" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="EXAMINATIONS_PRESCRIPTIONS" Member="PRESCRIPTIONS" ThisKey="id" OtherKey="examination_id" Type="PRESCRIPTIONS" />
      <Association Name="APPLICATIONS_EXAMINATIONS" Member="APPLICATIONS" ThisKey="application_id" OtherKey="id" Type="APPLICATIONS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDERS" Member="ORDERS">
    <Type Name="ORDERS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prescription_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="pharmacy_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="PHARMACIST_ORDERS" Member="PHARMACIST" ThisKey="pharmacy_id" OtherKey="id" Type="PHARMACIST" IsForeignKey="true" />
      <Association Name="PRESCRIPTIONS_ORDERS" Member="PRESCRIPTIONS" ThisKey="prescription_id" OtherKey="id" Type="PRESCRIPTIONS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PATIENT" Member="PATIENT">
    <Type Name="PATIENT">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="PATIENT_APPLICATIONS" Member="APPLICATIONS" ThisKey="id" OtherKey="patient_id" Type="APPLICATIONS" />
    </Type>
  </Table>
  <Table Name="dbo.PHARMACIST" Member="PHARMACIST">
    <Type Name="PHARMACIST">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="native_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="support_delivery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="support_preorder" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="PHARMACIST_ORDERS" Member="ORDERS" ThisKey="id" OtherKey="pharmacy_id" Type="ORDERS" />
      <Association Name="PHARMACIST_PHARMACIST_HOLIDAYS" Member="PHARMACIST_HOLIDAYS" ThisKey="id" OtherKey="pharmacy_id" Type="PHARMACIST_HOLIDAYS" />
      <Association Name="PHARMACIST_PHARMACIST_OPENTIMES" Member="PHARMACIST_OPENTIMES" ThisKey="id" OtherKey="pharmacy_id" Type="PHARMACIST_OPENTIMES" />
    </Type>
  </Table>
  <Table Name="dbo.PHARMACIST_HOLIDAYS" Member="PHARMACIST_HOLIDAYS">
    <Type Name="PHARMACIST_HOLIDAYS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pharmacy_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="away_start" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="away_close" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="PHARMACIST_PHARMACIST_HOLIDAYS" Member="PHARMACIST" ThisKey="pharmacy_id" OtherKey="id" Type="PHARMACIST" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHARMACIST_OPENTIMES" Member="PHARMACIST_OPENTIMES">
    <Type Name="PHARMACIST_OPENTIMES">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pharmacy_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="day_of_the_week" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="opentime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="closetime" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Association Name="PHARMACIST_PHARMACIST_OPENTIMES" Member="PHARMACIST" ThisKey="pharmacy_id" OtherKey="id" Type="PHARMACIST" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRESCRIPTIONS" Member="PRESCRIPTIONS">
    <Type Name="PRESCRIPTIONS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="examination_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="doucments_path" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="PRESCRIPTIONS_ORDERS" Member="ORDERS" ThisKey="id" OtherKey="prescription_id" Type="ORDERS" />
      <Association Name="EXAMINATIONS_PRESCRIPTIONS" Member="EXAMINATIONS" ThisKey="examination_id" OtherKey="id" Type="EXAMINATIONS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SPECIALIZATIONS" Member="SPECIALIZATIONS">
    <Type Name="SPECIALIZATIONS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="SPECIALIZATIONS_SPECIALIZATIONS_OF_DOCTORS" Member="SPECIALIZATIONS_OF_DOCTORS" ThisKey="id" OtherKey="specicalization_id" Type="SPECIALIZATIONS_OF_DOCTORS" />
    </Type>
  </Table>
  <Table Name="dbo.SPECIALIZATIONS_OF_DOCTORS" Member="SPECIALIZATIONS_OF_DOCTORS">
    <Type Name="SPECIALIZATIONS_OF_DOCTORS">
      <Column Name="id" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="specicalization_id" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="DOCTORS_SPECIALIZATIONS_OF_DOCTORS" Member="DOCTORS" ThisKey="doctor_id" OtherKey="id" Type="DOCTORS" IsForeignKey="true" />
      <Association Name="SPECIALIZATIONS_SPECIALIZATIONS_OF_DOCTORS" Member="SPECIALIZATIONS" ThisKey="specicalization_id" OtherKey="id" Type="SPECIALIZATIONS" IsForeignKey="true" />
    </Type>
  </Table>
</Database>